### ISSUE TITLE
Aanmaken rechtendocument

### ISSUE THREAD

**Issue by Arilith** [Arilith/ELO#9]
Wie kan wat, wanneer en hoe?

**Comment by TeunSpithoven** [comment]
Geen idee hoe dit werkt

**Comment by Arilith** [comment]
> Geen idee hoe dit werkt

Simpelweg een document opstellen:
Docent kan huiswerk invoeren, cijfers invoeren
Leerling kan huiswerk inzien, cijfers inzien
IT beheer kan wachtwoorden aanpassen, 

et cetera.
